version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend-app
    ports:
      - "8080:8080"
    volumes:
      - backend-data:/data

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app

volumes:
  backend-data:
